# Generated by Django 5.2 on 2025-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_homepage_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerimage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
