# Generated by Django 4.2.8 on 2025-07-24 12:01

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="organisation",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Organisation name", "max_length": 100, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Organisation URL link", "label": "Organisation URL", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                },
                help_text="List of organisation links in the footer",
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="services",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Serive name", "max_length": 100, "required": True}),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Service URL link", "label": "Service URL", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                },
                help_text="List of link services in the footer",
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="tools_and_data",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Tool and Data name", "max_length": 100, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Tool and data URL link", "label": "Tool and Data URL", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                },
                help_text="List of tool and data links in the footer",
            ),
        ),
    ]
