# Generated by Django 4.2.8 on 2025-07-31 09:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("home", "0006_alter_footer_organisation_alter_footer_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="services",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Service name", "max_length": 100, "required": True}),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Service URL link", "label": "Service URL", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                },
                help_text="List of link services in the footer",
            ),
        ),
        migrations.CreateModel(
            name="Navbar",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "menu_links",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Menu item name", "max_length": 100, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Menu item URL", "label": "Menu URL", "required": True},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                        },
                        help_text="List of menu items in the navbar",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="A high quality logo image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Navbar Logo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
