# Generated by Django 4.2.8 on 2025-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("home", "0007_alter_footer_services_navbar"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="A high quality footer logo image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Footer Logo",
            ),
        ),
    ]
