# Generated by Django 4.2.16 on 2025-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_sitetheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapserverConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service_provider",
                    models.CharField(
                        default="IGAD Climate Prediction and Applications Center (ICPAC)",
                        help_text="Name of service provider",
                        max_length=200,
                    ),
                ),
                (
                    "provider_url",
                    models.CharField(
                        default="https://www.icpac.net", help_text="Service provider's website URL", max_length=100
                    ),
                ),
                (
                    "office_country",
                    models.CharField(
                        default="Kenya",
                        help_text="Name of the country where service proivider offices are located",
                        max_length=100,
                    ),
                ),
                (
                    "office_city",
                    models.CharField(
                        default="Naiobi",
                        help_text="Name of the city where service proivider offices are located",
                        max_length=100,
                    ),
                ),
                (
                    "physical_address",
                    models.CharField(
                        default="Ngong, Kibiko Area, Next to KHIBIT",
                        help_text="Physica address of the service proivider",
                        max_length=100,
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        default="disaster-risk-management@igad.int",
                        help_text="contact email address through which service provider can be reached for support and feedback",
                        max_length=100,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        default="IGAD DRM Programme",
                        help_text="Name of contact division, unit or department within data proverder's organization",
                        max_length=200,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="english", help_text="Platform's default language. Any value is accepted", max_length=20
                    ),
                ),
                (
                    "service_fee",
                    models.TextField(
                        blank=True,
                        default="The Service is provided free of charge and on an 'AS IS' and 'AS AVAILABLE' basis. We make no warranties, express or implied, regarding the service's reliability, availability, or accuracy.",
                        help_text="service charge details if the service is provided at a fee",
                        null=True,
                    ),
                ),
                (
                    "use_terms",
                    models.TextField(
                        blank=True,
                        default="By accessing or using our Service, you agree to be bound by our Terms and Conditions of service. If you disagree with any part of the terms, then you do not have permission to access the Service.",
                        help_text="terms of service use",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapserver/Mapcache Configuration Option",
                "verbose_name_plural": "Mapserver/Mapcache Configuration Options",
            },
        ),
    ]
