# Generated by Django 4.2.16 on 2025-11-05 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_mapserverconfig_service_purpose_and_more"),
        ("home", "0012_remove_footer_organisation_remove_footer_services_and_more"),
    ]

    operations = []
