# Generated by Django 4.2.16 on 2025-12-16 16:47

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_add_map_preview_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='show_utility_bar',
            field=models.BooleanField(default=True, help_text='Display utility bar above the main navigation', verbose_name='Show Utility Bar'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='utility_email',
            field=models.EmailField(blank=True, help_text='Email address shown in utility bar', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='utility_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text displayed for the link', 'label': 'Link Text', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "The URL this link points to (e.g., '/' for home, '/about/', or 'https://example.com')", 'label': 'URL', 'max_length': 500}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check to open this link in a new browser tab', 'label': 'Open in new tab', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('url', 1), ('open_in_new_tab', 2)]], {})}, help_text='Quick links shown in utility bar', verbose_name='Quick Links'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='utility_phone',
            field=models.CharField(blank=True, help_text='Phone number shown in utility bar', max_length=50, verbose_name='Contact Phone'),
        ),
    ]
