# Generated by Django 5.2 on 2025-05-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_image_2",
            field=models.ForeignKey(
                blank=True,
                help_text="Second slide image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Banner Image 2",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_image_3",
            field=models.ForeignKey(
                blank=True,
                help_text="Third slide image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Banner Image 3",
            ),
        ),
    ]
