# Generated by Django 4.2.8 on 2025-07-24 11:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("home", "0004_alter_bannerimage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A short text to display below the logo", verbose_name="Logo Description"
                    ),
                ),
                (
                    "services",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Service name link",
                                    "label": "Serive name",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Service URL link", "label": "Service URL", "required": True},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                        },
                        help_text="List of link services in the footer",
                    ),
                ),
                (
                    "tools_and_data",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tool and data name link",
                                    "label": "Tool and Data name",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Tool and data URL link", "label": "Tool and Data URL", "required": True},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                        },
                        help_text="List of tool and data links in the footer",
                    ),
                ),
                (
                    "organisation",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Organisation name link",
                                    "label": "Organisation name",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Organisation URL link", "label": "Organisation URL", "required": True},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("name", 0), ("url", 1)]], {"icon": "link"}),
                        },
                        help_text="List of organisation links in the footer",
                    ),
                ),
                ("facebook", models.URLField(blank=True, help_text="Facebook page URL")),
                ("twitter", models.URLField(blank=True, help_text="Twitter profile URL")),
                ("youtube", models.URLField(blank=True, help_text="YouTube channel URL")),
                ("linkedin", models.URLField(blank=True, help_text="LinkedIn page URL")),
                ("github", models.URLField(blank=True, help_text="GitHub repo URL")),
                ("podcast", models.URLField(blank=True, help_text="Podcast feed URL")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
