# Generated by Django 4.2.8 on 2025-09-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_footer_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Name for this theme", max_length=100)),
                (
                    "primary_color",
                    models.CharField(
                        default="#034930", help_text="Main brand color (navbar, footer, primary buttons)", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#198754", help_text="Secondary color (buttons, highlights)", max_length=7
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#fbc02d", help_text="Accent color (call-to-action elements)", max_length=7
                    ),
                ),
                ("primary_text_color", models.CharField(default="#ffffff", help_text="Main text color", max_length=7)),
                (
                    "secondary_text_color",
                    models.CharField(default="#333333", help_text="Secondary text color", max_length=7),
                ),
                (
                    "background_color",
                    models.CharField(default="#ffffff", help_text="Main background color", max_length=7),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Site Theme",
                "verbose_name_plural": "Site Themes",
            },
        ),
    ]
