# Generated by Django 4.2.16 on 2025-10-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_mapserverconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapserverconfig",
            options={"verbose_name": "WMS/WFS Configuration", "verbose_name_plural": "WMS/WFS Configurations"},
        ),
        migrations.AlterField(
            model_name="mapserverconfig",
            name="email_address",
            field=models.CharField(
                default="disaster-risk-management@igad.int",
                help_text="Contact email address through which service provider can be reached for support and feedback",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mapserverconfig",
            name="service_fee",
            field=models.TextField(
                blank=True,
                default="The Service is provided free of charge and on an 'AS IS' and 'AS AVAILABLE' basis. We make no warranties, express or implied, regarding the service's reliability, availability, or accuracy.",
                help_text="Service charge details if the service is provided at a fee",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mapserverconfig",
            name="use_terms",
            field=models.TextField(
                blank=True,
                default="By accessing or using our Service, you agree to be bound by our Terms and Conditions of service. If you disagree with any part of the terms, then you do not have permission to access the Service.",
                help_text="Terms of service use",
                null=True,
            ),
        ),
    ]
