# Generated by Django 4.2.16 on 2025-10-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_mapserverconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapserverconfig",
            name="service_purpose",
            field=models.TextField(
                default="The East Africa Hazards Watch enables the monitoring of extreme events—such as droughts, cyclones, desert locust infestations, heavy rainfall, floods, and crop failures—that can have severe and widespread impacts across the region",
                help_text="descriptive text that explains purpose and objectives of this service",
            ),
        ),
        migrations.AddField(
            model_name="mapserverconfig",
            name="service_title",
            field=models.CharField(
                default="East Africa Hazards Watch (EAHW)",
                help_text="descriptive text/title that can be use to identify this data system",
                max_length=500,
            ),
        ),
    ]
