# Generated by Django 4.2.16 on 2025-11-04 06:29

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_mapserverconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='services',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='tools_and_data',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='menu_links',
        ),
        migrations.AddField(
            model_name='footer',
            name='sections',
            field=wagtail.fields.StreamField([('section', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The heading for this group of links', 'label': 'Title', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text displayed for the link', 'label': 'Link Text', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "The URL this link points to (e.g., '/' for home, '/about/', or 'https://example.com')", 'label': 'URL', 'max_length': 500}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check to open this link in a new browser tab', 'label': 'Open in new tab', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 1), ('url', 2), ('open_in_new_tab', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Add links for this section', 'label': 'Links'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {})}, help_text='Add footer sections with custom titles and links'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='menu_items',
            field=wagtail.fields.StreamField([('link', 3), ('dropdown', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text displayed for the link', 'label': 'Link Text', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "The URL this link points to (e.g., '/' for home, '/about/', or 'https://example.com')", 'label': 'URL', 'max_length': 500}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check to open this link in a new browser tab', 'label': 'Open in new tab', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('url', 1), ('open_in_new_tab', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'The heading for this group of links', 'label': 'Title', 'max_length': 100}), 5: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Add links for this section', 'label': 'Links'}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('links', 5)]], {})}, help_text='Add menu links and dropdown menus'),
        ),
    ]
