# Generated by Django 4.2.16 on 2025-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_language_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='enable_wave_animation',
            field=models.BooleanField(default=False, help_text='Show animated wave effect on the homepage hero section', verbose_name='Enable Wave Animation'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='wave_color_1',
            field=models.CharField(default='#e0f7fa', help_text='Lightest wave color - top layer', max_length=7, verbose_name='Wave Color 1 (Lightest)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='wave_color_2',
            field=models.CharField(default='#4dd0e1', help_text='Middle wave color', max_length=7, verbose_name='Wave Color 2 (Middle)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='wave_color_3',
            field=models.CharField(default='#0097a7', help_text='Darkest wave color - bottom layer', max_length=7, verbose_name='Wave Color 3 (Darkest)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='wave_height',
            field=models.IntegerField(default=150, help_text='Height of the wave animation area in pixels', verbose_name='Wave Height (px)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='wave_opacity',
            field=models.IntegerField(default=60, help_text='Opacity of the wave animation (0-100)', verbose_name='Wave Opacity (%)'),
        ),
    ]
