# Generated by Django 4.2.16 on 2025-12-16 16:31

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_create_multimodal_clustered_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='action_cards',
            field=wagtail.fields.StreamField([('action', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g., 'Monitor Flooding', 'Track Rainfall'", 'label': 'Title', 'max_length': 100}), 1: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'help_text': 'Select an icon for this action', 'label': 'Icon'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Brief description of what users can do', 'label': 'Description', 'max_length': 200}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "URL to link to (e.g., '/mapviewer/', '/reports/')", 'label': 'Link URL', 'max_length': 500}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'help_text': "Text for the action link (e.g., 'Open Map', 'View Reports')", 'label': 'Link Text', 'max_length': 50}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('description', 2), ('link_url', 3), ('link_text', 4)]], {'label': 'Action Card'})}, help_text="Action cards for the 'What You Can Do' section", null=True, verbose_name='What You Can Do'),
        ),
    ]
