# Generated by Django 4.2.16 on 2025-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_add_action_cards_to_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='map_preview_subtitle',
            field=models.CharField(blank=True, default='Real-time flood extent and forecast data across East Africa', max_length=500, verbose_name='Map Preview Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_preview_title',
            field=models.CharField(blank=True, default='Live Flood Monitoring', max_length=200, verbose_name='Map Preview Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_map_preview',
            field=models.BooleanField(default=True, help_text='Display an interactive map preview on the homepage', verbose_name='Show Map Preview'),
        ),
    ]
