# Generated by Django 4.2.16 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_add_image_to_action_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(help_text='ID of the Geomanager category', unique=True, verbose_name='Category ID')),
                ('description', models.CharField(help_text='Short description for homepage display', max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category Description',
                'verbose_name_plural': 'Category Descriptions',
            },
        ),
    ]
