# Generated by Django 4.2.16 on 2026-01-10 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_create_admin_clipped_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalClusterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_clustering', models.BooleanField(default=True, help_text='Enable clustering of multimodal forecast points on the map', verbose_name='Enable Clustering')),
                ('warning_threshold', models.FloatField(default=10.0, help_text='Daily average discharge above this value triggers Warning level', verbose_name='Warning Threshold (m³/s)')),
                ('alarm_threshold', models.FloatField(default=50.0, help_text='Daily average discharge above this value triggers Alarm level', verbose_name='Alarm Threshold (m³/s)')),
                ('emergency_threshold', models.FloatField(default=100.0, help_text='Daily average discharge above this value triggers Emergency level', verbose_name='Emergency Threshold (m³/s)')),
                ('normal_color', models.CharField(default='#808080', help_text='Color for normal alert level (hex format, e.g., #808080)', max_length=7, verbose_name='Normal Color')),
                ('warning_color', models.CharField(default='#ffc107', help_text='Color for warning alert level (hex format, e.g., #ffc107)', max_length=7, verbose_name='Warning Color')),
                ('alarm_color', models.CharField(default='#ff9800', help_text='Color for alarm alert level (hex format, e.g., #ff9800)', max_length=7, verbose_name='Alarm Color')),
                ('emergency_color', models.CharField(default='#d32f2f', help_text='Color for emergency alert level (hex format, e.g., #d32f2f)', max_length=7, verbose_name='Emergency Color')),
                ('cluster_max_zoom', models.IntegerField(default=12, help_text='Maximum zoom level at which points are clustered (0-22)', verbose_name='Cluster Max Zoom')),
                ('cluster_radius', models.IntegerField(default=50, help_text='Radius in pixels for grouping points into clusters', verbose_name='Cluster Radius')),
            ],
            options={
                'verbose_name': 'Multimodal Cluster Settings',
                'verbose_name_plural': 'Multimodal Cluster Settings',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_text',
            field=models.CharField(default='Explore Map', help_text='Text displayed on the hero banner button', max_length=50, verbose_name='Banner Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_url',
            field=models.CharField(default='/mapviewer/', help_text='URL the banner button links to', max_length=255, verbose_name='Banner Button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_you_can_do_title',
            field=models.CharField(default='What You Can Do', help_text='Title displayed above the action cards section', max_length=100, verbose_name='What You Can Do Section Title'),
        ),
        migrations.AlterField(
            model_name='categorydescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='partners',
            field=wagtail.fields.StreamField([('partner', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the partner organization', 'label': 'Description', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image/Logo/Banner'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL', 'max_length': 500, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1), ('image', 2), ('url', 3)]], {})}, help_text='Add partner organizations with logos', verbose_name='Partners'),
        ),
        migrations.CreateModel(
            name='MultimodalDataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for this upload batch', max_length=255, verbose_name='Title')),
                ('data_date', models.DateField(help_text='Date of the forecast data', verbose_name='Forecast Date')),
                ('source', models.CharField(choices=[('upload', 'File Upload'), ('ftp', 'FTP Server'), ('drive', 'Google Drive')], default='upload', max_length=20, verbose_name='Data Source')),
                ('csv_file', models.FileField(blank=True, help_text='Single Zone CSV file or ZIP containing multiple Zone*.csv files', null=True, upload_to='multimodal/csv/', verbose_name='CSV File')),
                ('shapefile', models.FileField(blank=True, help_text='ZIP file containing shapefile (.shp, .shx, .dbf, .prj) for control points', null=True, upload_to='multimodal/shapefiles/', verbose_name='Control Points Shapefile')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('processing_log', models.TextField(blank=True, help_text='Log messages from processing', verbose_name='Processing Log')),
                ('feature_count', models.IntegerField(default=0, verbose_name='Total Features')),
                ('matched_count', models.IntegerField(default=0, verbose_name='Features with Data')),
                ('geojson_data', models.JSONField(blank=True, null=True, verbose_name='Generated GeoJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multimodal_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimodal Data Upload',
                'verbose_name_plural': 'Multimodal Data Uploads',
                'ordering': ['-data_date', '-created_at'],
            },
        ),
    ]
