# Generated by Django 4.2.16 on 2026-01-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_add_dynamic_banner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_question',
            field=models.CharField(blank=True, default='Is there flood risk in East Africa?', help_text="Question displayed in the Q&A style hero (e.g., 'Is there flood risk in East Africa?'). The answer is dynamically populated from forecast data.", max_length=255, verbose_name='Hero Question'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='alarm_threshold',
            field=models.FloatField(default=300.0, help_text='Daily average discharge above this value triggers Alarm level', verbose_name='Alarm Threshold (m³/s)'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='emergency_threshold',
            field=models.FloatField(default=450.0, help_text='Daily average discharge above this value triggers Emergency level', verbose_name='Emergency Threshold (m³/s)'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='warning_threshold',
            field=models.FloatField(default=150.0, help_text='Daily average discharge above this value triggers Warning level', verbose_name='Warning Threshold (m³/s)'),
        ),
    ]
