# Generated by Django 4.2.28 on 2026-02-11 18:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0036_update_alert_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Display name for the category', max_length=100, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is enabled', verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this category is selected by default on page load', verbose_name='Default Selected')),
                ('geomanager_category_id', models.IntegerField(blank=True, help_text='Optional: Link to a Geomanager category for layer data', null=True, verbose_name='Geomanager Category ID')),
                ('icon', models.ForeignKey(blank=True, help_text='Icon image for the category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Category Icon')),
            ],
            options={
                'verbose_name': 'Map Category',
                'verbose_name_plural': 'Map Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MapExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='Text displayed on the button', max_length=100, verbose_name='Link Label')),
                ('url', models.CharField(help_text='Full URL or relative path (e.g., /reports/)', max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Open in New Tab')),
                ('button_color', models.CharField(default='#ff9800', max_length=7, verbose_name='Button Color')),
            ],
            options={
                'verbose_name': 'Map External Link',
                'verbose_name_plural': 'Map External Links',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MapLegendItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alert_level', models.CharField(choices=[('emergency', 'Emergency'), ('alarm', 'Alarm'), ('warning', 'Warning'), ('normal', 'Normal')], help_text='The alert level this legend item represents', max_length=20, verbose_name='Alert Level')),
                ('label', models.CharField(help_text="Display label (e.g., 'Emergency: Extreme flood risk')", max_length=100, verbose_name='Label')),
                ('icon', models.ForeignKey(blank=True, help_text='Icon image for this legend item (same as used on map)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Legend Icon')),
            ],
            options={
                'verbose_name': 'Map Legend Item',
                'verbose_name_plural': 'Map Legend Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='floodbulletinpage',
            name='header_logo',
        ),
        migrations.RemoveField(
            model_name='floodbulletinpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='floodbulletinpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='reportindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reportindexpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='situationreportpage',
            name='header_logo',
        ),
        migrations.RemoveField(
            model_name='situationreportpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='situationreportpage',
            name='search_image',
        ),
        migrations.DeleteModel(
            name='MergedDeterministicGeoJSON',
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_title',
            field=models.CharField(default='Latest Situation of Flood Conditions', help_text="Main title displayed above the map (e.g., 'Latest Situation of Flood Conditions')", max_length=200, verbose_name='Dashboard Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='legend_title',
            field=models.CharField(default='Current Flood Alerts', help_text='Title displayed above the map legend', max_length=100, verbose_name='Legend Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='point_filter_mode',
            field=models.CharField(choices=[('all', 'All Points'), ('active', 'Active Points Only (Warning+)'), ('alarm', 'Alarm and Above'), ('emergency', 'Emergency Only')], default='all', help_text='Filter which forecast points are displayed on the map', max_length=20, verbose_name='Point Filter'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_category_menu',
            field=models.BooleanField(default=False, help_text="Display category menu inside the map (like 'Our Hazards Watch')", verbose_name='Show Category Menu'),
        ),
        migrations.AlterField(
            model_name='enabledlanguage',
            name='language_code',
            field=models.CharField(choices=[('ab', 'Abkhaz'), ('ace', 'Acehnese'), ('ach', 'Acholi'), ('aa', 'Afar'), ('af', 'Afrikaans'), ('sq', 'Albanian'), ('alz', 'Alur'), ('am', 'Amharic'), ('ar', 'Arabic'), ('hy', 'Armenian'), ('as', 'Assamese'), ('av', 'Avar'), ('awa', 'Awadhi'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ban', 'Balinese'), ('bal', 'Baluchi'), ('bm', 'Bambara'), ('bci', 'Baoulé'), ('ba', 'Bashkir'), ('eu', 'Basque'), ('btx', 'Batak Karo'), ('bts', 'Batak Simalungun'), ('bbc', 'Batak Toba'), ('be', 'Belarusian'), ('bem', 'Bemba'), ('bn', 'Bengali'), ('bew', 'Betawi'), ('bho', 'Bhojpuri'), ('bik', 'Bikol'), ('bs', 'Bosnian'), ('br', 'Breton'), ('bg', 'Bulgarian'), ('bua', 'Buryat'), ('yue', 'Cantonese'), ('ca', 'Catalan'), ('ceb', 'Cebuano'), ('ch', 'Chamorro'), ('ce', 'Chechen'), ('ny', 'Chichewa'), ('zh-CN', 'Chinese'), ('chk', 'Chuukese'), ('cv', 'Chuvash'), ('co', 'Corsican'), ('crh', 'Crimean Tatar (Cyrillic)'), ('crh-Latn', 'Crimean Tatar (Latin)'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('fa-AF', 'Dari'), ('dv', 'Dhivehi'), ('din', 'Dinka'), ('doi', 'Dogri'), ('dov', 'Dombe'), ('nl', 'Dutch'), ('dyu', 'Dyula'), ('dz', 'Dzongkha'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('ee', 'Ewe'), ('fo', 'Faroese'), ('fj', 'Fijian'), ('tl', 'Filipino'), ('fi', 'Finnish'), ('fon', 'Fon'), ('fr', 'French'), ('fr-CA', 'French (Canada)'), ('fy', 'Frisian'), ('fur', 'Friulian'), ('ff', 'Fulani'), ('gaa', 'Ga'), ('gl', 'Galician'), ('ka', 'Georgian'), ('de', 'German'), ('el', 'Greek'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ht', 'Haitian Creole'), ('cnh', 'Hakha Chin'), ('ha', 'Hausa'), ('haw', 'Hawaiian'), ('iw', 'Hebrew'), ('hil', 'Hiligaynon'), ('hi', 'Hindi'), ('hmn', 'Hmong'), ('hu', 'Hungarian'), ('hrx', 'Hunsrik'), ('iba', 'Iban'), ('is', 'Icelandic'), ('ig', 'Igbo'), ('ilo', 'Ilocano'), ('id', 'Indonesian'), ('iu-Latn', 'Inuktut (Latin)'), ('iu', 'Inuktut (Syllabics)'), ('ga', 'Irish'), ('it', 'Italian'), ('jam', 'Jamaican Patois'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('kac', 'Jingpo'), ('kl', 'Kalaallisut'), ('kn', 'Kannada'), ('kr', 'Kanuri'), ('pam', 'Kapampangan'), ('kk', 'Kazakh'), ('kha', 'Khasi'), ('km', 'Khmer'), ('cgg', 'Kiga'), ('kg', 'Kikongo'), ('rw', 'Kinyarwanda'), ('ktu', 'Kituba'), ('trp', 'Kokborok'), ('kv', 'Komi'), ('gom', 'Konkani'), ('ko', 'Korean'), ('kri', 'Krio'), ('ku', 'Kurdish (Kurmanji)'), ('ckb', 'Kurdish (Sorani)'), ('ky', 'Kyrgyz'), ('lo', 'Lao'), ('ltg', 'Latgalian'), ('la', 'Latin'), ('lv', 'Latvian'), ('lij', 'Ligurian'), ('li', 'Limburgish'), ('ln', 'Lingala'), ('lt', 'Lithuanian'), ('lmo', 'Lombard'), ('lg', 'Luganda'), ('luo', 'Luo'), ('lb', 'Luxembourgish'), ('mk', 'Macedonian'), ('mad', 'Madurese'), ('mai', 'Maithili'), ('mak', 'Makassar'), ('mg', 'Malagasy'), ('ms', 'Malay'), ('ms-Arab', 'Malay (Jawi)'), ('ml', 'Malayalam'), ('mt', 'Maltese'), ('mam', 'Mam'), ('gv', 'Manx'), ('mi', 'Maori'), ('mr', 'Marathi'), ('mh', 'Marshallese'), ('mwr', 'Marwadi'), ('mfe', 'Mauritian Creole'), ('chm', 'Meadow Mari'), ('mni-Mtei', 'Meiteilon (Manipuri)'), ('min', 'Minang'), ('lus', 'Mizo'), ('mn', 'Mongolian'), ('my', 'Myanmar (Burmese)'), ('nhe', 'Nahuatl (Eastern Huasteca)'), ('ndc-ZW', 'Ndau'), ('nr', 'Ndebele (South)'), ('new', 'Nepalbhasa (Newari)'), ('ne', 'Nepali'), ('bm-Nkoo', 'NKo'), ('no', 'Norwegian'), ('nus', 'Nuer'), ('oc', 'Occitan'), ('or', 'Odia (Oriya)'), ('om', 'Oromo'), ('os', 'Ossetian'), ('pag', 'Pangasinan'), ('pap', 'Papiamento'), ('ps', 'Pashto'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese (Brazil)'), ('pt-PT', 'Portuguese (Portugal)'), ('pa', 'Punjabi (Gurmukhi)'), ('pa-Arab', 'Punjabi (Shahmukhi)'), ('qu', 'Quechua'), ('kek', 'Qʼeqchiʼ'), ('rom', 'Romani'), ('ro', 'Romanian'), ('rn', 'Rundi'), ('ru', 'Russian'), ('se', 'Sami (North)'), ('sm', 'Samoan'), ('sg', 'Sango'), ('sa', 'Sanskrit'), ('sat-Latn', 'Santali (Latin)'), ('sat', 'Santali (Ol Chiki)'), ('gd', 'Scots Gaelic'), ('nso', 'Sepedi'), ('sr', 'Serbian'), ('st', 'Sesotho'), ('crs', 'Seychellois Creole'), ('shn', 'Shan'), ('sn', 'Shona'), ('scn', 'Sicilian'), ('szl', 'Silesian'), ('sd', 'Sindhi'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('so', 'Somali'), ('es', 'Spanish'), ('su', 'Sundanese'), ('sus', 'Susu'), ('sw', 'Swahili'), ('ss', 'Swati'), ('sv', 'Swedish'), ('ty', 'Tahitian'), ('tg', 'Tajik'), ('ber-Latn', 'Tamazight'), ('ber', 'Tamazight (Tifinagh)'), ('ta', 'Tamil'), ('tt', 'Tatar'), ('te', 'Telugu'), ('tet', 'Tetum'), ('th', 'Thai'), ('bo', 'Tibetan'), ('ti', 'Tigrinya'), ('tiv', 'Tiv'), ('tpi', 'Tok Pisin'), ('to', 'Tongan'), ('lua', 'Tshiluba'), ('ts', 'Tsonga'), ('tn', 'Tswana'), ('tcy', 'Tulu'), ('tum', 'Tumbuka'), ('tr', 'Turkish'), ('tk', 'Turkmen'), ('tyv', 'Tuvan'), ('ak', 'Twi'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('ug', 'Uyghur'), ('uz', 'Uzbek'), ('ve', 'Venda'), ('vec', 'Venetian'), ('vi', 'Vietnamese'), ('war', 'Waray'), ('cy', 'Welsh'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('sah', 'Yakut'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('yua', 'Yucatec Maya'), ('zap', 'Zapotec'), ('zu', 'Zulu')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='member_countries',
            field=wagtail.fields.StreamField([('country', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('AF', 'Afghanistan'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas (The)'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Côte d'Ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('CD', 'Democratic Republic of the Congo'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('KP', 'North Korea'), ('MK', 'North Macedonia'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia'), ('KR', 'South Korea'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Türkiye'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States of America'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', 'Vatican City'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('VG', 'Virgin Islands (British)'), ('VI', 'Virgin Islands (U.S.)'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], 'help_text': 'Select a country - flag will load automatically', 'label': 'Country'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL', 'max_length': 500, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('country', 0), ('url', 1)]], {})}, help_text='Select countries - flags load automatically', verbose_name='Member Countries'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='alarm_threshold',
            field=models.FloatField(default=500.0, help_text='Daily average discharge above this value triggers Alarm level', verbose_name='Alarm Threshold (m³/s)'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='emergency_threshold',
            field=models.FloatField(default=750.0, help_text='Daily average discharge above this value triggers Emergency level', verbose_name='Emergency Threshold (m³/s)'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='normal_color',
            field=models.CharField(default='#4caf50', help_text='Color for normal alert level (hex format, e.g., #4caf50)', max_length=7, verbose_name='Normal Color'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='warning_threshold',
            field=models.FloatField(default=300.0, help_text='Daily average discharge above this value triggers Warning level', verbose_name='Warning Threshold (m³/s)'),
        ),
        migrations.DeleteModel(
            name='FloodBulletinPage',
        ),
        migrations.DeleteModel(
            name='ReportIndexPage',
        ),
        migrations.DeleteModel(
            name='SituationReportPage',
        ),
        migrations.AddField(
            model_name='maplegenditem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_legend_items', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='mapexternallink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_external_links', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_categories', to='home.homepage'),
        ),
    ]
