# Generated by Django 4.2.28 on 2026-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_add_unmanaged_expert_assessment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictRiskLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_type', models.CharField(choices=[('hydrologist', 'Hydrologist'), ('meteorologist', 'Meteorologist')], max_length=20)),
                ('assessment_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('admin1', models.CharField(max_length=100, verbose_name='Admin Level 1')),
                ('admin2', models.CharField(max_length=100, verbose_name='Admin Level 2')),
                ('gid_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='GID 2')),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('watch', 'Watch'), ('warning', 'Warning'), ('alarm', 'Alarm'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'District Risk Level',
                'verbose_name_plural': 'District Risk Levels',
                'db_table': 'district_risk_levels',
                'ordering': ['-assessment_date', 'country', 'admin1'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_type', models.CharField(choices=[('hydrologist', 'Hydrologist'), ('meteorologist', 'Meteorologist')], max_length=20)),
                ('assessment_date', models.DateField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('country_code', models.CharField(default='REGION', max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('watch', 'Watch'), ('warning', 'Warning'), ('alarm', 'Alarm'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('assessment_comment', models.TextField()),
                ('affected_areas', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Expert Assessment',
                'verbose_name_plural': 'Expert Assessments',
                'db_table': 'expert_assessments',
                'ordering': ['-assessment_date', '-created_at'],
                'managed': False,
            },
        ),
    ]
