# Generated by Django 4.2 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_add_report_snapshots_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessment_id", models.IntegerField(unique=True)),
                ("snapshot_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Report Snapshot",
                "verbose_name_plural": "Report Snapshots",
                "db_table": "report_snapshots",
                "ordering": ["-updated_at"],
                "managed": False,
            },
        ),
    ]

