# Generated by Django 4.2.16 on 2026-02-16 18:55

from django.db import migrations
import home.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_harden_admin_scope_clipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homepage_member_countries',
            field=wagtail.fields.StreamField(
                [('country', home.blocks.CountryBlock())],
                blank=True,
                help_text='Member countries displayed in the homepage partners strip',
                verbose_name='Homepage Member Countries',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homepage_partners',
            field=wagtail.fields.StreamField(
                [('partner', home.blocks.LogoItemBlock())],
                blank=True,
                help_text='Partner logos displayed in the homepage partners strip',
                verbose_name='Homepage Partners',
            ),
        ),
    ]
