# Generated by Django 4.2.28 on 2026-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_footer_partners_page_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcategory',
            name='data_url',
            field=models.CharField(blank=True, help_text='GeoJSON endpoint URL (for points mode), e.g. /api/v1/multimodal/geojson/', max_length=500, verbose_name='Data URL'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='legend_items_json',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of legend items, e.g. [{"label": "Emergency", "color": "#d32f2f"}]', verbose_name='Legend Items'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='render_mode',
            field=models.CharField(choices=[('points', 'GeoJSON Points'), ('wms-raster', 'WMS Raster'), ('impact-score', 'Impact Risk Score')], default='points', help_text='How this layer renders on the map', max_length=20, verbose_name='Render Mode'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='unavailable_message',
            field=models.CharField(blank=True, help_text="Message shown when this layer's data is unavailable", max_length=200, verbose_name='Unavailable Message'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='value_field',
            field=models.CharField(blank=True, help_text="GeoJSON property field for point values, e.g. 'daily_avg'", max_length=50, verbose_name='Value Field'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='value_label',
            field=models.CharField(blank=True, help_text="Display label for the value, e.g. 'Discharge'", max_length=50, verbose_name='Value Label'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='value_unit',
            field=models.CharField(blank=True, help_text="Unit for values, e.g. 'm³/s'", max_length=20, verbose_name='Value Unit'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='wms_base_url',
            field=models.TextField(blank=True, help_text='WMS tile URL template (for wms-raster mode). Use {layer} and {bbox-epsg-3857} as placeholders. Example: /mapserver/?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS={layer}&WIDTH=256&HEIGHT=256&SRS=EPSG:3857&BBOX={bbox-epsg-3857}', verbose_name='WMS Base URL'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='wms_layer_name',
            field=models.CharField(blank=True, help_text='MapServer layer name for WMS requests, e.g. wrf_extreme_very_heavy', max_length=100, verbose_name='WMS Layer Name'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='normal_color',
            field=models.CharField(default='#b0b0b0', help_text='Color for normal alert level (hex format, e.g., #b0b0b0)', max_length=7, verbose_name='Normal Color'),
        ),
    ]
