# Generated by Django 5.2 on 2026-02-21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_exclude_eritrea_from_admin_geometries'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="Button label, e.g. 'WHCA Project'", max_length=100, verbose_name='Scope Name')),
                ('key', models.SlugField(help_text="Unique key passed as ?scope= to the API, e.g. 'whca'", max_length=50, verbose_name='Scope Key')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scope button is shown', verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text="If checked, this scope loads by default instead of 'All Countries'", verbose_name='Default on Load')),
                ('country_codes_iso2', models.CharField(blank=True, help_text="Comma-separated ISO-2 codes for member flag filtering, e.g. 'SD,SS,UG,ET,RW'", max_length=200, verbose_name='Country Codes (ISO-2)')),
                ('country_codes_iso3', models.CharField(blank=True, help_text="Comma-separated ISO-3 codes for admin boundary filtering, e.g. 'ETH,RWA,SSD,SDN,UGA'", max_length=200, verbose_name='Country Codes (ISO-3)')),
                ('partner_keys', models.TextField(blank=True, help_text="Comma-separated normalized partner name keys to show, e.g. 'wmo,wateratheart,netherlandsredcross'", verbose_name='Partner Keys')),
                ('country_section_title', models.CharField(blank=True, help_text="e.g. 'Nile Basin Flood Situation'", max_length=200, verbose_name='Country Section Title')),
                ('dashboard_title', models.CharField(blank=True, help_text="e.g. 'Latest Situation of Nile Basin Flood Conditions'", max_length=200, verbose_name='Dashboard Title')),
                ('show_basin_overlay', models.BooleanField(default=False, help_text='Show the Nile basin boundary line when this scope is active', verbose_name='Show Basin Overlay')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_scopes', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Map Scope',
                'verbose_name_plural': 'Map Scopes',
                'ordering': ['sort_order'],
            },
        ),
    ]
