# Generated by Django 4.2.29 on 2026-03-13 05:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0079_use_perpoint_thresholds_in_cluster_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Custom background color. Overrides the site-wide theme navbar color when set.', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='An optional background image for the navbar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Navbar Background Image'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='background_opacity',
            field=models.IntegerField(default=55, help_text='Overlay opacity over the background image (0 = fully transparent, 100 = fully opaque). Default is 55.', verbose_name='Background Overlay Opacity'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo_text_part_1',
            field=models.CharField(blank=True, default='EAST AFRICA', help_text='First part of the text-based logo.', max_length=100, verbose_name='Logo Text Part 1'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo_text_part_2',
            field=models.CharField(blank=True, default='FLOOD', help_text='Second part of the text-based logo', max_length=100, verbose_name='Logo Text Part 2'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo_text_part_3',
            field=models.CharField(blank=True, default='WATCH', help_text='Third part of the text-based logo', max_length=100, verbose_name='Logo Text Part 3'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='theme_colored_lines',
            field=models.BooleanField(default=False, help_text='If checked, colored lines will be drawn below the navbar. Add custom lines below, or leave empty for default theme colors.', verbose_name='Display Color Lines'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='partners',
            field=wagtail.fields.StreamField([('partner', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the partner organization', 'label': 'Description', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image/Logo/Banner'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL', 'max_length': 500, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable this to feature the partner in the homepage partner strip', 'label': 'Major Partner (Show on Homepage)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1), ('image', 2), ('url', 3), ('show_on_homepage', 4)]], {})}, help_text='Add partner organizations with logos', verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='point_filter_mode',
            field=models.CharField(choices=[('all', 'All Points'), ('active', 'Active Points Only (Moderate+)'), ('alarm', 'Severe and Above'), ('emergency', 'Extreme Only')], default='all', help_text='Filter which forecast points are displayed on the map', max_length=20, verbose_name='Point Filter'),
        ),
        migrations.AlterField(
            model_name='mapcategory',
            name='legend_items_json',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of legend items, e.g. [{"label": "Extreme", "color": "#d32f2f"}]', verbose_name='Legend Items'),
        ),
        migrations.AlterField(
            model_name='mapcategory',
            name='wms_base_url',
            field=models.TextField(blank=True, help_text='Tile URL template (for wms-raster mode). Example: /cog-tiles/collections/{collection}/tiles/WebMercatorQuad/{z}/{x}/{y}.png?assets=data', verbose_name='WMS Base URL'),
        ),
        migrations.AlterField(
            model_name='mapcategory',
            name='wms_layer_name',
            field=models.CharField(blank=True, help_text='STAC collection ID or layer identifier, e.g. wrf_extreme_very_heavy', max_length=100, verbose_name='WMS Layer Name'),
        ),
        migrations.AlterField(
            model_name='maplegenditem',
            name='alert_level',
            field=models.CharField(choices=[('emergency', 'Extreme'), ('alarm', 'Severe'), ('warning', 'Moderate'), ('normal', 'Normal')], help_text='The alert level this legend item represents', max_length=20, verbose_name='Alert Level'),
        ),
        migrations.AlterField(
            model_name='maplegenditem',
            name='label',
            field=models.CharField(help_text="Display label (e.g., 'Extreme: Severe flood risk')", max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='alarm_color',
            field=models.CharField(default='#2f83d2', help_text='Color for Severe (Alarm) alert level (hex format, e.g., #2f83d2)', max_length=7, verbose_name='Severe Color'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='alarm_threshold',
            field=models.FloatField(default=500.0, help_text='Daily average discharge above this value triggers Severe (Alarm) level', verbose_name='Severe Threshold (m³/s)'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='emergency_color',
            field=models.CharField(default='#1e1a97', help_text='Color for Extreme (Emergency) alert level (hex format, e.g., #1e1a97)', max_length=7, verbose_name='Extreme Color'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='emergency_threshold',
            field=models.FloatField(default=750.0, help_text='Daily average discharge above this value triggers Extreme (Emergency) level', verbose_name='Extreme Threshold (m³/s)'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='normal_color',
            field=models.CharField(default='#b0bec5', help_text='Color for normal alert level (hex format, e.g., #b0bec5)', max_length=7, verbose_name='Normal Color'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='warning_color',
            field=models.CharField(default='#b8f0f0', help_text='Color for Moderate (Warning) alert level (hex format, e.g., #b8f0f0)', max_length=7, verbose_name='Moderate Color'),
        ),
        migrations.AlterField(
            model_name='multimodalclustersettings',
            name='warning_threshold',
            field=models.FloatField(default=300.0, help_text='Daily average discharge above this value triggers Moderate (Warning) level', verbose_name='Moderate Threshold (m³/s)'),
        ),
        migrations.CreateModel(
            name='NavbarColorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('color', models.CharField(default='#034930', help_text='Pick a color for this line', max_length=7, verbose_name='Line Color')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_lines', to='home.navbar')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
