# Generated by Django 4.2.28 on 2026-03-02 05:11

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("storylines", "0002_create_sample_storyline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storylinepage",
            name="chapters",
            field=wagtail.fields.StreamField(
                [("chapter", 42)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Chapter Title", "max_length": 200},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "h3",
                                "h4",
                                "blockquote",
                            ],
                            "help_text": "The story content for this chapter",
                            "label": "Narrative Text",
                        },
                    ),
                    2: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "Map center longitude (e.g., 38.5)",
                            "label": "Center Longitude",
                        },
                    ),
                    3: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "Map center latitude (e.g., 5.0)",
                            "label": "Center Latitude",
                        },
                    ),
                    4: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 5,
                            "help_text": "Map zoom (0-18)",
                            "label": "Zoom Level",
                        },
                    ),
                    5: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "Map rotation in degrees (0-360)",
                            "label": "Bearing",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "Map tilt in degrees (0-60)",
                            "label": "Pitch",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("center_lon", 2),
                                ("center_lat", 3),
                                ("zoom", 4),
                                ("bearing", 5),
                                ("pitch", 6),
                            ]
                        ],
                        {
                            "help_text": "Where the map should fly to for this chapter",
                            "label": "Map View",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional short name shown in the chapter card",
                            "label": "Label",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Public URL to a GeoJSON file for this chapter overlay",
                            "label": "GeoJSON URL",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fill", "Fill Polygon"),
                                ("line", "Line"),
                                ("circle", "Point Circles"),
                            ],
                            "label": "Layer Type",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#38bdf8",
                            "help_text": "CSS color (for example #38bdf8 or rgba(56,189,248,1))",
                            "label": "Color",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 0.45,
                            "label": "Opacity",
                            "max_value": 1,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 2,
                            "label": "Line Width",
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Point Radius",
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("url", 9),
                                ("layer_type", 10),
                                ("color", 11),
                                ("opacity", 12),
                                ("line_width", 13),
                                ("point_radius", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {
                            "help_text": "GeoJSON flood layers to render when this chapter is active",
                            "label": "Map Overlays",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fly", "Fly To (animated)"),
                                ("jump", "Jump To (instant)"),
                                ("ease", "Ease To (slow pan)"),
                            ],
                            "label": "Map Transition",
                        },
                    ),
                    18: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "For timeline playback - start of date range",
                            "label": "Event Start Date",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "For timeline playback - end of date range",
                            "label": "Event End Date",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Uploaded Image"},
                    ),
                    21: ("wagtail.blocks.URLBlock", (), {"label": "Image URL"}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Alt Text", "max_length": 200},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Caption", "max_length": 500, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 21), ("alt", 22), ("caption", 23)]],
                        {"icon": "image", "label": "External Image"},
                    ),
                    25: ("wagtail.blocks.URLBlock", (), {"label": "Embed URL"}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 200, "required": False},
                    ),
                    27: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 400, "label": "Height (px)"},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 25), ("title", 26), ("height", 27)]],
                        {"icon": "media", "label": "Embed (iframe)"},
                    ),
                    29: ("wagtail.blocks.URLBlock", (), {"label": "Video URL"}),
                    30: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Poster Image URL", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Autoplay", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Muted", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Loop", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 29),
                                ("title", 26),
                                ("poster_url", 30),
                                ("caption", 23),
                                ("autoplay", 31),
                                ("muted", 32),
                                ("loop", 33),
                            ]
                        ],
                        {"icon": "media", "label": "External Video"},
                    ),
                    35: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Video File"},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("file", 35),
                                ("title", 26),
                                ("poster_url", 30),
                                ("caption", 23),
                                ("autoplay", 31),
                                ("muted", 32),
                                ("loop", 33),
                            ]
                        ],
                        {"icon": "media", "label": "Uploaded Video"},
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image", 20),
                                ("external_image", 24),
                                ("embed", 28),
                                ("external_video", 34),
                                ("uploaded_video", 36),
                            ]
                        ],
                        {
                            "help_text": "Images, embeds, or external media for this chapter",
                            "label": "Media",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Reference title or description",
                            "label": "Title",
                            "max_length": 300,
                        },
                    ),
                    39: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Link to the source", "label": "URL"},
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 38), ("url", 39)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (40,),
                        {
                            "help_text": "Source links for this chapter",
                            "label": "References",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("prose", 1),
                                ("map_state", 7),
                                ("map_overlays", 16),
                                ("transition", 17),
                                ("date_start", 18),
                                ("date_end", 19),
                                ("media", 37),
                                ("references", 41),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="The narrative chapters that drive the scrollytelling experience",
                verbose_name="Story Chapters",
            ),
        ),
    ]
