# Generated by Django 4.2.16 on 2025-10-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0057_alter_rasterfilelayer_options_alter_wmslayer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmslayer",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geomanager.rasterstyle",
                verbose_name="Tiles Color Style",
            ),
        ),
    ]
