# Generated by Django 4.2.16 on 2025-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0058_wmslayer_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmslayer",
            name="can_clip",
            field=models.BooleanField(
                default=True,
                help_text="Check to enable clipping by boundary or drawn shapes",
                verbose_name="Enable Clipping by shape",
            ),
        ),
    ]
