# Generated by Django 4.2.16 on 2025-11-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0062_merge_20251112_1006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wmsrasterdatasetsync",
            options={"verbose_name": "WMS Raster Sync Option", "verbose_name_plural": "WMS Raster Sync Options"},
        ),
        migrations.AlterField(
            model_name="dataset",
            name="dataset_slug",
            field=models.SlugField(
                blank=True,
                help_text="A human-readable hypen separated text to uniquely identify the dataset for the purpose of updating from data ingestion jobs and visualization using mapserver/mapcache",
                max_length=200,
                null=True,
                verbose_name="human-readable dataset unique identifier text",
            ),
        ),
        migrations.AlterField(
            model_name="watcherconfig",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily data product (product updated every day)"),
                    ("dekadal", "Dekadal (10-day periods: days 1, 11, 21)"),
                    ("pentadal", "Pentadal (5-day periods: days 1, 6, 11, 16, 21, 26)"),
                    ("monthly", "Monthly data product (updated every month)"),
                    ("seasonal", "Seasonal data product (updated every season)"),
                    ("yearly", "Yearly data product (updated every year)"),
                    ("static", "Static data product (never updated)"),
                ],
                default="dekadal",
                help_text="Type of periodic dates for this dataset (affects date generation and backfilling)",
                max_length=20,
                verbose_name="Period Type",
            ),
        ),
    ]
