# Generated by Django 4.2.16 on 2025-11-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0063_alter_wmsrasterdatasetsync_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wmsrequestlayer",
            name="name",
            field=models.SlugField(
                help_text="WMS Layer is requested by using this name in the LAYERS parameter of a GetMap request.",
                max_length=250,
                verbose_name="name",
            ),
        ),
    ]
