# Generated by Django 4.2.16 on 2026-03-03 07:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0066_geomanagersettings_filter_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geomanagersettings",
            name="filter_types",
            field=wagtail.fields.StreamField(
                [("filter_type", 17)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Unique key, e.g. "admin" or "cluster"', "label": "Filter type identifier"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Shown in map viewer dropdown, e.g. "Filter by Admin"', "label": "Display label"},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Base URL to fetch boundary data from", "label": "Boundary API URL"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Set to "Admin" for admin boundaries. Leave empty for cluster types — root-level selection code is used instead.',
                            "label": "Fixed project_name",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "code",
                            "help_text": "API response field used as boundary code for all levels. Individual levels can override this with their own code field.",
                            "label": "Default code field",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "name",
                            "help_text": "API response field used as display label for all levels. Individual levels can override this with their own name field.",
                            "label": "Default name field",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Section heading"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Dropdown placeholder"}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Value sent as admin_level in tile params when selected",
                            "label": "Admin level value",
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Optional identifier so child levels can reference this level\'s selected code via {variable_name} in extra_api_params. e.g. "cluster" lets a child write project_name={cluster}.',
                            "label": "Variable name",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'API param that receives the immediate parent\'s selected code. Empty for root level. e.g. "unit_id" or "project_name".',
                            "label": "Parent param name",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Adds with_bbox=true to the API request so boundaries include bounding box data for map fitting. Uncheck for root levels whose items have no geographic extent (e.g. cluster names).",
                            "label": "Include bbox in request",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Fixed query params as key=value pairs separated by &. Use {variable_name} to inject an ancestor\'s selected code. e.g. "admin_level=0&project_name={cluster}"',
                            "label": "Extra API params",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override the filter type's default code field for this level only. Leave empty to use the filter type default.",
                            "label": "Code field override",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override the filter type's default name field for this level only. Leave empty to use the filter type default.",
                            "label": "Name field override",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 6),
                                ("placeholder", 7),
                                ("admin_level", 8),
                                ("variable_name", 9),
                                ("parent_param", 10),
                                ("include_bbox", 11),
                                ("extra_api_params", 12),
                                ("code_field", 13),
                                ("name_field", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {"label": "Hierarchy levels", "min_num": 1}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("value", 0),
                                ("label", 1),
                                ("boundary_api_url", 2),
                                ("fixed_project_name", 3),
                                ("default_code_field", 4),
                                ("default_name_field", 5),
                                ("levels", 16),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Define filter types shown in the map viewer. Order = dropdown order.",
                null=True,
                verbose_name="Filter Types",
            ),
        ),
    ]
