# Generated by Django 4.2.16 on 2025-11-10 12:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("home", "0013_merge_20251105_1104"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="github",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="podcast",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="youtube",
        ),
        migrations.AddField(
            model_name="footer",
            name="copyright_organization",
            field=models.CharField(
                default="ICPAC",
                help_text="Organization name for copyright notice (e.g., 'ICPAC', 'Your Organization')",
                max_length=100,
                verbose_name="Copyright Organization",
            ),
        ),
        migrations.AddField(
            model_name="footer",
            name="social_links",
            field=wagtail.fields.StreamField(
                [("social_link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the social media platform (e.g., Facebook, Twitter)",
                            "label": "Platform Name",
                            "max_length": 50,
                        },
                    ),
                    1: (
                        "wagtailiconchooser.blocks.IconChooserBlock",
                        (),
                        {"help_text": "Select an icon for this social media platform", "label": "Icon"},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Full URL to your social media profile", "label": "Profile URL"},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("name", 0), ("icon", 1), ("url", 2)]], {}),
                },
                help_text="Add social media links with custom names and icons",
            ),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tabicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Browser tab icon (favicon).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Tab Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
