# Generated by Django 4.2.16 on 2025-12-09 12:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_remove_footer_facebook_remove_footer_github_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "Tab Icon", "verbose_name_plural": "Tab Icons"},
        ),
        migrations.AlterField(
            model_name="footer",
            name="social_links",
            field=wagtail.fields.StreamField(
                [("social_link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the social media platform (e.g., Facebook, Twitter)",
                            "label": "Platform Name",
                            "max_length": 50,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Select an icon for this social media platform", "label": "Icon"},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Full URL to your social media profile", "label": "Profile URL"},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("name", 0), ("icon", 1), ("url", 2)]], {}),
                },
                help_text="Add social media links with custom names and icons",
            ),
        ),
    ]
