# Generated by Django 4.2.16 on 2026-01-19 07:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0015_alter_sitesettings_options_alter_footer_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='An optional background image for the navbar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Navbar Background Image'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social_links',
            field=wagtail.fields.StreamField([('social_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the social media platform (e.g., Facebook, Twitter)', 'label': 'Platform Name', 'max_length': 50}), 1: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'help_text': 'Select an icon for this social media platform', 'label': 'Icon'}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL to your social media profile', 'label': 'Profile URL'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('icon', 1), ('url', 2)]], {})}, help_text='Add social media links with custom names and icons'),
        ),
    ]
