# Generated by Django 4.2.16 on 2026-01-19 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0016_navbar_background_image_alter_footer_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='An optional background image for the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Background Image'),
        ),
    ]
