# Generated by Django 4.2.16 on 2026-01-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_footer_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='logo_text_part_1',
            field=models.CharField(blank=True, default='EAST AFRICA', help_text='First part of the text-based logo.', max_length=100, verbose_name='Logo Text Part 1'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo_text_part_2',
            field=models.CharField(blank=True, default='HAZARDS', help_text='Second part of the text-based logo', max_length=100, verbose_name='Logo Text Part 2'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo_text_part_3',
            field=models.CharField(blank=True, default='WATCH', help_text='Third part of the text-based logo', max_length=100, verbose_name='Logo Text Part 3'),
        ),
    ]
