# Generated by Django 4.2.16 on 2026-01-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_navbar_logo_text_part_1_navbar_logo_text_part_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='theme_colored_lines',
            field=models.BooleanField(default=False, help_text='If checked, three horizontal theme colored lines will be drawn above the footer.', verbose_name='Display Color Lines'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='theme_colored_lines',
            field=models.BooleanField(default=False, help_text='If checked, three horizontal theme colored lines will be drawn below the navbar.', verbose_name='Display Color Lines'),
        ),
    ]
