# Generated by Django 4.2.16 on 2026-02-21 11:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_footer_theme_colored_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='background_opacity',
            field=models.IntegerField(default=55, help_text='Overlay opacity over the background image (0 = fully transparent, 100 = fully opaque). Default is 55.', verbose_name='Background Overlay Opacity'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='background_opacity',
            field=models.IntegerField(default=55, help_text='Overlay opacity over the background image (0 = fully transparent, 100 = fully opaque). Default is 55.', verbose_name='Background Overlay Opacity'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='theme_colored_lines',
            field=models.BooleanField(default=False, help_text='If checked, colored lines will be drawn above the footer. Add custom lines below, or leave empty for default theme colors.', verbose_name='Display Color Lines'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='theme_colored_lines',
            field=models.BooleanField(default=False, help_text='If checked, colored lines will be drawn below the navbar. Add custom lines below, or leave empty for default theme colors.', verbose_name='Display Color Lines'),
        ),
        migrations.CreateModel(
            name='NavbarColorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('color', models.CharField(default='#034930', help_text='Pick a color for this line', max_length=7, verbose_name='Line Color')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_lines', to='home.navbar')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('color', models.CharField(default='#034930', help_text='Pick a color for this line', max_length=7, verbose_name='Line Color')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_lines', to='home.footer')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
