# Generated by Django 4.2.16 on 2026-03-04 02:39

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_languagesettings_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="social_links",
            field=wagtail.fields.StreamField(
                [("social_link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the social media platform (e.g., Facebook, Twitter)",
                            "label": "Platform Name",
                            "max_length": 50,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Font Awesome class, e.g. 'fab fa-facebook' or 'fab fa-x-twitter'",
                            "label": "Icon",
                            "max_length": 100,
                        },
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Full URL to your social media profile", "label": "Profile URL"},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("name", 0), ("icon", 1), ("url", 2)]], {}),
                },
                help_text="Add social media links with custom names and icons",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("am", "Amharic"),
                    ("so", "Somali"),
                    ("om", "Oromo"),
                    ("ti", "Tigrinya"),
                    ("ar", "Arabic"),
                    ("fr", "French"),
                    ("rw", "Kinyarwanda"),
                    ("rn", "Rundi"),
                    ("lg", "Luganda"),
                    ("zh-CN", "Chinese (Simplified)"),
                ],
                help_text="Select a Google Translate supported language.",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
