# Generated by Django 4.2.16 on 2026-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_footer_background_opacity_navbar_background_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Custom background color. Overrides the site-wide theme footer color when set.', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Custom background color. Overrides the site-wide theme navbar color when set.', max_length=7, verbose_name='Background Color'),
        ),
    ]
