# Generated by Django 4.2.16 on 2026-03-04 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_alter_footer_social_links_alter_language_language"),
        ("home", "0021_footer_background_color_navbar_background_color"),
    ]

    operations = []
