# Generated by Django 4.2.16 on 2026-03-04 10:53

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20260304_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='member_states_title',
            field=models.CharField(blank=True, default='Member States', help_text='Title for the member states section', max_length=255, verbose_name='Member States Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_member_states',
            field=models.BooleanField(default=False, help_text='Display the Member States flags section on the homepage', verbose_name='Show Member States Section'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social_links',
            field=wagtail.fields.StreamField([('social_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the social media platform (e.g., Facebook, Twitter)', 'label': 'Platform Name', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Font Awesome (v4.7.0) class, e.g. 'fab fa-facebook' or 'fab fa-x-twitter'", 'label': 'Icon', 'max_length': 100}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL to your social media profile', 'label': 'Profile URL'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('icon', 1), ('url', 2)]], {})}, help_text='Add social media links with custom names and icons'),
        ),
    ]
