# Generated by Django 4.2.16 on 2026-03-04 12:29

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_homepage_member_states_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='member_states',
            field=wagtail.fields.StreamField([('member_state', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the member state', 'label': 'Country Name', 'max_length': 100}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Flag image for the member state', 'label': 'Flag Image'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('flag', 1)]], {})}, help_text='Add member states with their flags', null=True, verbose_name='Member States'),
        ),
    ]
