# Generated by Django 4.2.16 on 2026-03-30 08:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        ('home', '0025_footer_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='feature_blocks',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 1: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 150, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('description', 2)]], {'label': 'Feature'})}, null=True, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='member_states',
            field=wagtail.fields.StreamField([('member_state', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bi', 'Burundi'), ('dj', 'Djibouti'), ('er', 'Eritrea'), ('et', 'Ethiopia'), ('ke', 'Kenya'), ('rw', 'Rwanda'), ('so', 'Somalia'), ('ss', 'South Sudan'), ('sd', 'Sudan'), ('tz', 'Tanzania'), ('ug', 'Uganda')], 'help_text': 'Select the member state — flag will load automatically', 'label': 'Country'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override display name (leave blank to use country name)', 'label': 'Display Name', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Tick if this country is part of the current project (e.g. WHCA)', 'label': 'Project Country', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('country_code', 0), ('name', 1), ('is_project_country', 2)]], {})}, help_text='Add member states with their flags', null=True, verbose_name='Member States'),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Hero Subtitle')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Full project description displayed below the hero', verbose_name='Project Description')),
                ('scope_key', models.CharField(blank=True, help_text="Passed as ?scope= to mapviewer/reports for filtering (e.g., 'whca')", max_length=50, verbose_name='Scope Key')),
                ('partner_groups', wagtail.fields.StreamField([('partner_group', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Group Title', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'fa-handshake', 'label': 'Icon CSS class', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Partner Name', 'max_length': 100}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Partner Logo', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Website URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 3), ('logo', 4), ('url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Partners'}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('description', 2), ('partners', 7)]], {})}, verbose_name='Partner Groups')),
                ('member_countries_title', models.CharField(blank=True, default='Member Countries', max_length=255)),
                ('member_countries', wagtail.fields.StreamField([('member_state', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bi', 'Burundi'), ('dj', 'Djibouti'), ('er', 'Eritrea'), ('et', 'Ethiopia'), ('ke', 'Kenya'), ('rw', 'Rwanda'), ('so', 'Somalia'), ('ss', 'South Sudan'), ('sd', 'Sudan'), ('tz', 'Tanzania'), ('ug', 'Uganda')], 'help_text': 'Select the member state — flag will load automatically', 'label': 'Country'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override display name (leave blank to use country name)', 'label': 'Display Name', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Tick if this country is part of the current project (e.g. WHCA)', 'label': 'Project Country', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('country_code', 0), ('name', 1), ('is_project_country', 2)]], {})}, verbose_name='Member Countries')),
                ('cta_buttons', wagtail.fields.StreamField([('cta_button', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display on the button', 'label': 'Button Title', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "URL to link to. Can be relative (e.g. '/mapviewer/') or full (e.g. 'https://example.com')", 'label': 'URL', 'max_length': 500}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1)]], {})}, verbose_name='Call to Action Buttons')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('project_url', models.URLField(blank=True, verbose_name='Project Website URL')),
                ('project_url_label', models.CharField(blank=True, default='More information here', max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Background Image')),
                ('project_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Project Logo')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
