# Generated by Django 4.2.16 on 2025-10-30 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0058_dataset_api_url_dataset_auto_update_frequency_and_more"),
        ("geomanager", "0059_wmslayer_can_clip"),
    ]

    operations = []
