# Generated by Django 4.2.16 on 2025-12-09 07:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0064_alter_wmsrequestlayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectortilelayer',
            name='popup_config',
            field=wagtail.fields.StreamField([('popup_fields', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Data Key', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Popup Label', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('string', 'String'), ('number', 'Number')], 'label': 'Data Type'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Hidden (for chart data)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('data_key', 0), ('label', 1), ('data_type', 2), ('hidden', 3)]], {'label': 'Popup Fields'})}, null=True, verbose_name='Map Popup Configuration'),
        ),
    ]
