# Generated by Django 4.2.16 on 2026-03-03 03:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "to_address",
                    models.EmailField(
                        help_text="Address that submitted messages are forwarded to.",
                        max_length=254,
                        verbose_name="Recipient Email",
                    ),
                ),
                (
                    "thank_you_message",
                    models.TextField(
                        default="Thank you for your message. We will get back to you shortly.",
                        help_text="Shown above the form after a successful submission.",
                        verbose_name="Thank You Message",
                    ),
                ),
                (
                    "panel_heading",
                    models.CharField(default="Get in Touch", max_length=100, verbose_name="Panel Heading"),
                ),
                (
                    "panel_intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Short intro text shown below the panel heading.",
                        verbose_name="Panel Introduction",
                    ),
                ),
                (
                    "info_blocks",
                    wagtail.fields.StreamField(
                        [("info", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Font Awesome class, e.g. 'fas fa-location-dot' or 'fas fa-envelope'",
                                    "label": "Icon",
                                    "max_length": 100,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Title", "max_length": 100}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Use links for email addresses (mailto:) and URLs.",
                                    "label": "Content",
                                },
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("icon", 0), ("title", 1), ("content", 2)]], {}),
                        },
                        help_text="Add contact info entries (address, email, social links, etc.).",
                        verbose_name="Contact Info Blocks",
                    ),
                ),
                (
                    "banner_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Full-width image displayed at the top of the page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Banner Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
