# Generated by Django 4.2.16 on 2026-03-04 11:13

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MapWidgetSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "show_map_widget",
                    models.BooleanField(
                        default=False,
                        help_text="Display the interactive map section on the homepage",
                        verbose_name="Show Map Widget",
                    ),
                ),
                (
                    "map_widget_heading",
                    models.CharField(
                        blank=True, default="Explore Our Data", max_length=200, verbose_name="Map Widget Heading"
                    ),
                ),
                ("map_center_lat", models.FloatField(default=0.0, verbose_name="Map Center Latitude")),
                ("map_center_lng", models.FloatField(default=20.0, verbose_name="Map Center Longitude")),
                ("map_zoom", models.IntegerField(default=4, verbose_name="Map Initial Zoom")),
                (
                    "map_datasets",
                    wagtail.fields.StreamField(
                        [("dataset", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Label shown on the toggle button",
                                    "label": "Dataset Title",
                                    "max_length": 100,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("wms", "WMS"), ("xyz", "XYZ Tiles"), ("geojson", "GeoJSON URL")],
                                    "label": "Layer Type",
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "WMS base URL, XYZ tile URL ({z}/{x}/{y}), or GeoJSON endpoint",
                                    "label": "Layer URL",
                                    "max_length": 1000,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Comma-separated WMS LAYERS parameter value (WMS only)",
                                    "label": "WMS Layer Names",
                                    "max_length": 500,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Load this dataset when the map first opens",
                                    "label": "Active by Default",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("layer_type", 1),
                                        ("layer_url", 2),
                                        ("wms_layers", 3),
                                        ("default_active", 4),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Add 3–4 datasets editors can toggle on the homepage map",
                        verbose_name="Map Datasets",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Map Widget",
                "verbose_name_plural": "Homepage Map Widget",
            },
        ),
    ]
