# Generated by Django 4.2.16 on 2026-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapwidget", "0002_mapdatasetentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapwidgetsettings",
            name="map_cta_button_label",
            field=models.CharField(
                blank=True, default="Explore on Hazards Watch →", max_length=100, verbose_name="CTA Button Label"
            ),
        ),
        migrations.AddField(
            model_name="mapwidgetsettings",
            name="map_cta_text",
            field=models.CharField(
                blank=True,
                default="For more risk information",
                help_text="Descriptive text shown to the left of the action button below the map",
                max_length=200,
                verbose_name="CTA Text",
            ),
        ),
    ]
