# Generated by Django 4.2.16 on 2026-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapwidget", "0004_mapwidgetsettings_boundary_dataset_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapdatasetentry",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Pick an icon for this dataset toggle button", max_length=150, verbose_name="Icon"
            ),
        ),
    ]
