# Generated by Django 4.2.16 on 2026-03-05 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapwidget", "0005_alter_mapdatasetentry_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mapwidgetsettings",
            name="map_center_lat",
        ),
        migrations.RemoveField(
            model_name="mapwidgetsettings",
            name="map_center_lng",
        ),
        migrations.RemoveField(
            model_name="mapwidgetsettings",
            name="map_zoom",
        ),
    ]
