# Generated by Django 4.2.16 on 2026-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapwidget", "0007_mapwidgetsettings_map_cta_button_label_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapwidgetsettings",
            name="map_cta_button_url",
            field=models.CharField(
                blank=True,
                default="/mapviewer",
                help_text="Link for the first action button (e.g. /mapviewer or https://example.com)",
                max_length=500,
                verbose_name="CTA Button 1 URL",
            ),
        ),
        migrations.AlterField(
            model_name="mapwidgetsettings",
            name="map_cta_button_url_2",
            field=models.CharField(
                blank=True,
                help_text="Link for the second action button (e.g. /mapviewer or https://example.com)",
                max_length=500,
                verbose_name="CTA Button 2 URL",
            ),
        ),
    ]
