# Generated by Django 4.2.16 on 2026-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwidget', '0011_mapdatasetentry_legend_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapdatasetentry',
            name='legend_title',
        ),
        migrations.RemoveField(
            model_name='mapwidgetsettings',
            name='map_cta_buttons',
        ),
        migrations.AddField(
            model_name='mapwidgetsettings',
            name='map_cta_button_label',
            field=models.CharField(blank=True, default='Explore on Hazards Watch', help_text='Text for the first action button', max_length=100, verbose_name='CTA Button 1 Label'),
        ),
        migrations.AddField(
            model_name='mapwidgetsettings',
            name='map_cta_button_label_2',
            field=models.CharField(blank=True, help_text='Text for the second action button (leave blank to hide)', max_length=100, verbose_name='CTA Button 2 Label'),
        ),
        migrations.AddField(
            model_name='mapwidgetsettings',
            name='map_cta_button_url',
            field=models.CharField(blank=True, default='/mapviewer', help_text='Link for the first action button (e.g. /mapviewer or https://example.com)', max_length=500, verbose_name='CTA Button 1 URL'),
        ),
        migrations.AddField(
            model_name='mapwidgetsettings',
            name='map_cta_button_url_2',
            field=models.CharField(blank=True, help_text='Link for the second action button (e.g. /mapviewer or https://example.com)', max_length=500, verbose_name='CTA Button 2 URL'),
        ),
        migrations.AlterField(
            model_name='mapwidgetsettings',
            name='map_cta_text',
            field=models.CharField(blank=True, default='For more risk information', help_text='Descriptive text shown to the left of the action buttons below the map', max_length=200, verbose_name='CTA Text'),
        ),
    ]
