# Generated by Django 4.2.16 on 2026-03-04 10:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Our Partners', help_text='Main heading for the partners page', max_length=255, verbose_name='Page Title')),
                ('page_subtitle', models.TextField(blank=True, help_text='Brief introduction or description for the partners page', null=True, verbose_name='Page Subtitle')),
                ('partners', wagtail.fields.StreamField([('partner', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the Project', 'label': 'Project Name', 'max_length': 200, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Logo of the partner organization', 'label': 'Partner Logo', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Brief description of the Project. You can add links within the text.', 'label': 'Description', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': "Partner's website URL", 'label': 'Website URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('description', 2), ('website_url', 3)]], {})}, help_text='Add partner organizations', null=True, verbose_name='Partners')),
                ('banner_image', models.ForeignKey(blank=True, help_text='Full-width image displayed at the top of the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page', models.Model),
        ),
    ]
