# Generated by Django 4.2.16 on 2026-03-11 04:24

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerspage",
            name="cta",
            field=wagtail.fields.StreamField(
                [("cta_button", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display on the button", "label": "Button Title", "max_length": 200},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "URL to link to. Can be relative (e.g. '/mapviewer/') or full (e.g. 'https://example.com')",
                            "label": "URL",
                            "max_length": 500,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("url", 1)]], {}),
                },
                help_text="Optional CTA button displayed below the partner cards. Leave empty to hide.",
                verbose_name="Call to Action Button",
            ),
        ),
    ]
