# Generated by Django 4.2.16 on 2025-11-12 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0061_watcherconfig_remove_dataset_api_url_and_more"),
        ("geomanager", "0061_wmsrasterdatasetsync_alter_dataset_period_type_and_more"),
    ]

    operations = []
