# Generated by Django 4.2.16 on 2025-12-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0064_alter_wmsrequestlayer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wmsrequestlayer",
            name="name",
            field=models.CharField(
                help_text="WMS Layer is requested by using this name in the LAYERS parameter of a GetMap request.",
                max_length=250,
                verbose_name="name",
            ),
        ),
    ]
