# Generated by Django 4.2.16 on 2026-03-02 13:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0065_alter_wmsrequestlayer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="geomanagersettings",
            name="filter_types",
            field=wagtail.fields.StreamField(
                [("filter_type", 14)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Unique key, e.g. "admin" or "cluster"', "label": "Filter type identifier"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Shown in map viewer dropdown, e.g. "Filter by Admin"', "label": "Display label"},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Base URL to fetch boundary data from", "label": "Boundary API URL"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Set to "Admin" for admin boundaries. Leave empty for cluster types — root-level selection code is used instead.',
                            "label": "Fixed project_name",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Section heading"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Dropdown placeholder"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Response field to use as boundary code", "label": "Code field"},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Response field to use as display label", "label": "Name field"},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Value sent as admin_level in tile params when selected",
                            "label": "Admin level value",
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"default": "0", "label": "Border level value"}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'API param receiving parent code. Empty for root level. e.g. "unit_id" (admin) or "project_name" (cluster)',
                            "label": "Parent param name",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Additional query params as key=value pairs separated by &. e.g. "with_bbox=true" or "admin_level=0&with_bbox=true"',
                            "label": "Extra API params",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 4),
                                ("placeholder", 5),
                                ("code_field", 6),
                                ("name_field", 7),
                                ("admin_level", 8),
                                ("border_level", 9),
                                ("parent_param", 10),
                                ("extra_api_params", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {"label": "Hierarchy levels", "min_num": 1}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("value", 0),
                                ("label", 1),
                                ("boundary_api_url", 2),
                                ("fixed_project_name", 3),
                                ("levels", 13),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Define filter types shown in the map viewer. Order = dropdown order.",
                null=True,
                verbose_name="Filter Types",
            ),
        ),
    ]
