"""
Django settings for geomanagerweb project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import environ
import sys

GEOMANAGER_PATH = '/home/koros/IGAD-ICPAC/Projects/FloodWatch/code/hazard_watch/geomanager'
if GEOMANAGER_PATH not in sys.path:
    sys.path.insert(0, GEOMANAGER_PATH)

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

CAP_COMPOSER_PATH = os.environ.get(
    'CAP_COMPOSER_PATH',
    os.path.join(BASE_DIR, 'capcomposer', 'src')
)
if CAP_COMPOSER_PATH not in sys.path:
    sys.path.insert(0, CAP_COMPOSER_PATH)

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    EMAIL_USE_TLS=(bool, True),
)

if os.path.exists(os.path.join(BASE_DIR, ".env")):
    # reading .env file
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Application definition
INSTALLED_APPS = [
    "home",
    "geomanager",
    # CAP Composer (Common Alerting Protocol)
    "capcomposer.capeditor",
    "capcomposer.cap",
    "wagtailmodelchooser",
    "wagtail_newsletter",
    "django_celery_beat",
    "daphne",
    "channels",
    "base",
    "django_deep_translator",
    "wagtail_localize",
    "wagtail_localize.locales",
    "adminboundarymanager",
    "django_large_image",
    "django_json_widget",
    "django_nextjs",
    "django_filters",
    "wagtail_color_panel",
    "wagtail_adminsortable",
    "wagtailhumanitarianicons",
    "wagtailiconchooser",
    "django_countries",
    "django_extensions",
    "wagtailfontawesomesvg",
    "wagtail_lazyimages",
    "django_cleanup.apps.CleanupConfig",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail.api.v2",
    "modelcluster",
    "taggit",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "rest_framework",
    "corsheaders",
    "wagtail_modeladmin",
    "wagtailcache",
    "wagtailmetadata",
    "django.contrib.admin",
    "django.contrib.gis",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Language switching
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "geomanagerweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "home.context_processors.theme_context",
                "home.context_processors.navbar_context",
                "home.context_processors.language_context",
                "home.context_processors.analytics_context",
            ],
        },
    },
]

WSGI_APPLICATION = "geomanagerweb.wsgi.application"
ASGI_APPLICATION = "geomanagerweb.asgi.application"
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {"default": env.db()}

# Set PostgreSQL search_path to use cms and gha schemas (no public schema)
# This ensures Django finds tables in the correct schemas
if "default" in DATABASES:
    if "OPTIONS" not in DATABASES["default"]:
        DATABASES["default"]["OPTIONS"] = {}
    DATABASES["default"]["OPTIONS"]["options"] = "-c search_path=cms,gha"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = env.str("TIME_ZONE", "UTC")

USE_I18N = True

USE_L10N = True

USE_TZ = True

# IGAD Member States Languages
# Djibouti (French, Arabic), Eritrea (Tigrinya, Arabic), Ethiopia (Amharic),
# Kenya (Swahili, English), Somalia (Somali, Arabic), South Sudan (English, Arabic),
# Sudan (Arabic), Uganda (English, Swahili)
LANGUAGES = [
    ("en", "English"),
    ("sw", "Swahili"),  # Kenya, Uganda, Tanzania
    ("ar", "العربية"),  # Arabic - Sudan, South Sudan, Djibouti, Somalia, Eritrea
    ("am", "አማርኛ"),  # Amharic - Ethiopia
    ("fr", "Français"),  # French - Djibouti
    ("so", "Soomaali"),  # Somali - Somalia
    ("om", "Oromoo"),  # Oromo - Ethiopia
]

# Wagtail content languages (same as LANGUAGES)
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES

# Enable Wagtail internationalization
WAGTAIL_I18N_ENABLED = True

# Locale paths for translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
    os.path.join(PROJECT_DIR, "locale"),
    os.path.join(BASE_DIR, "home", "locale"),
]

# Django
FORCE_SCRIPT_NAME = env.str("FORCE_SCRIPT_NAME", default="")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/4.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
# STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

STATICFILES_STORAGE = "base.storage.ManifestStaticFilesStorageNotStrict"

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"
if FORCE_SCRIPT_NAME != "":
    STATIC_URL = FORCE_SCRIPT_NAME + STATIC_URL

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# CSRF allowed origins
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", cast=None, default=[])

# Cross-Origin-Requests Settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", cast=None, default=[])

# Periodic watchers
ENABLE_PERIODIC_WATCHERS = True
WATCHER_CHECK_INTERVAL = 300  # (5 minutes)

if FORCE_SCRIPT_NAME != "":
    MEDIA_URL = FORCE_SCRIPT_NAME + MEDIA_URL

# Wagtail settings

WAGTAIL_SITE_NAME = env.str("WAGTAIL_SITE_NAME", "East Africa Flood Watch")

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = env.str("WAGTAILADMIN_BASE_URL", "")

# CMS Base URL - used for generating absolute URLs in API responses (e.g., media URLs)
# Set this in production/staging to ensure correct URLs regardless of proxy headers
CMS_BASE_URL = env.str("CMS_BASE_URL", "")

# Wagtail admin Url path
ADMIN_URL_PATH = env.str("ADMIN_URL_PATH", "admin")

NEXTJS_SETTINGS = {"nextjs_server_url": env.str("MAPVIEWER_SERVER_URL", None)}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "cache"),
        "KEY_PREFIX": "cms_cache",
        "TIMEOUT": 3600,  # one hour (in seconds)
    }
}
WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]
# RECAPTCHA Settings
RECAPTCHA_PUBLIC_KEY = env.str("RECAPTCHA_PUBLIC_KEY", "")
RECAPTCHA_PRIVATE_KEY = env.str("RECAPTCHA_PRIVATE_KEY", "")

GEOMANAGER_AUTO_INGEST_RASTER_DATA_DIR = env.str("GEOMANAGER_AUTO_INGEST_RASTER_DATA_DIR", "")

# Celery Configuration (uncomment when ready to enable scheduled tasks)
# CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", "redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"
# CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule - Scheduled Tasks
# from celery.schedules import crontab
# CELERY_BEAT_SCHEDULE = {
#     # Sync Multimodal forecast data daily at 14:30 UTC (17:30 EAT)
#     # FTP server updates around 17:00 EAT, this runs 30 min later
#     "sync-multimodal-daily": {
#         "task": "home.tasks.sync_multimodal_daily",
#         "schedule": crontab(hour=14, minute=30),
#     },
# }

# Multimodal FTP Configuration
MULTIMODAL_FTP_HOST = env.str("ENSEMBLE_FTP_HOST", "")
MULTIMODAL_FTP_PORT = env.int("ENSEMBLE_FTP_PORT", 21)
MULTIMODAL_FTP_USER = env.str("ENSEMBLE_FTP_USER", "")
MULTIMODAL_FTP_PASSWORD = env.str("ENSEMBLE_FTP_PASSWORD", "")
MULTIMODAL_FTP_DIR = env.str("ENSEMBLE_FTP_DIR", "")

# CAP Composer Configuration
CAP_CERT_PATH = env.str("CAP_CERT_PATH", default="")
CAP_PRIVATE_KEY_PATH = env.str("CAP_PRIVATE_KEY_PATH", default="")
CAP_SIGNATURE_METHOD = env.str("CAP_SIGNATURE_METHOD", default="RSA_SHA256")
CAP_MQTT_SECRET_KEY = env.str("CAP_MQTT_SECRET_KEY", default="")
CAP_ALLOW_EDITING = env.bool("CAP_ALLOW_EDITING", default=False)
